name: publish

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.5.2

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1

      - name: Publish to Buf Registry
        uses: bufbuild/buf-push-action@v1.1.1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'main'}}
